### ISSUE TITLE
Customizing Fonts

### ISSUE THREAD

**Issue by be5invis** [nk2028/tshet-uinh-autoderiver#24]
Is it possible to allow customizing fonts in the editor and the output?
I am recently working on a Tengwar notation so I need to introduce custom fonts for the editor and the output...

**Comment by graphemecluster** [comment]
Version 0.2 already supports some style operations such as font size and color. I can add font family support with slight changes to the code.

**Comment by be5invis** [comment]
@graphemecluster Docs about styles?

**Comment by graphemecluster** [comment]
Will, but we haven’t released v0.2 yet.

**Comment by graphemecluster** [comment]
Basically you return something like `` ({ f, b }) => f`Hello ${b`bold text`}` ``, but `font` isn’t supported yet.

**Comment by be5invis** [comment]
May need font customization for the UX too (like the dropdowns).

**Comment by ayaka14732** [comment]
因為這是系統字型或瀏覽器的功能，可以由用户自己解決（例如使用 CSS 插件）
