### ISSUE TITLE
CORS broken

### ISSUE THREAD

**Issue by syimyuzya** [nk2028/tshet-uinh-autoderiver#27]
(Note: The whole site is currently deployed on GH Pages to get around it.)

My Firefox showed messages like this:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://qieyun-autoderiver-1305783649.file.myqcloud.com/assets/index-BP6mtVv0.css. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

(PS I forgot to look into the request/response headers. If you need it, I can try deploying the COS version again to see it)

What works:

- Uploading assets to COS
- Manually opening the address on COS (not fetching with an HTML tag or script)
- Opening index.html (alone) on GH Pages

What breaks:
- Loading resources on COS from index.html

My suspection on what could possibly cause the problem:
- The assets are now located in the directory `/assets`, unlike before (was `/static`)
- The address of the site is now `https://nk2028.shn.hk/tshet-uinh-autoderiver/`, not `/qieyun-autoderiver`

**Comment by ayaka14732** [comment]
I will fix it today after my work!

**Comment by ayaka14732** [comment]
Fixed in https://github.com/nk2028/tshet-uinh-autoderiver/commit/7f0c0c0eb81ec559951e2f6dd1f1104a3f6efee0. Specifically, I created a new Tencent Cloud COS bucket to drop the old `qieyun-` prefix, and added CORS settings for the new bucket.

**Comment by ayaka14732** [comment]
Also deleted the old bucket as it's no longer used.
