### ISSUE TITLE
Spaces becoming narrower when selected in the editor

### ISSUE THREAD

**Issue by untunt** [nk2028/tshet-uinh-autoderiver#29]
![image](https://github.com/user-attachments/assets/eaafec53-ed3e-4400-852a-0710b9846c5e)

The selected spaces in the second line are added `width:4.1015625px` style. This seems unnecessary.

Always reproducible in Chrome and Edge on Windows.

**Comment by graphemecluster** [comment]
Does 2de7ea8a4b594eeb8a6c42689732a6be2e3f8f82 (incidentally) fix the issue?

**Comment by graphemecluster** [comment]
Did 2de7ea8a4b594eeb8a6c42689732a6be2e3f8f82 incidentally fix the issue?

**Comment by untunt** [comment]
Great, it's fixed.
