### ISSUE TITLE
諄韻去留問題

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-autoderiver#42]
[韻典網說有諄韻](https://ytenx.org/kyonh/yonh)，但這推導器好像不收，那即是有還是無？

**Comment by syimyuzya** [comment]
諄韻是《廣韻》增的，不是《切韻》的。較新的切韻音系構擬一般不單獨考慮諄韻，「推導」則更不需要。

若確有必要反映諄韻，可以用 `真韻 合口 非 B類` 這一條件判斷。
