### ISSUE TITLE
將推導器例文改成音韻學奇文，如《施氏食獅史》、《郭沫若沒出息》之類

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-autoderiver#46]
這些奇文比起現在的例文更能展現音韻學特徵。

**Comment by ayaka14732** [comment]
https://github.com/nk2028/tshet-uinh-text-label/pull/4#pullrequestreview-2474176015

**Comment by syimyuzya** [comment]
可以加入 tshet-uinh-text-label～

至於預設文章，要的效果就是「演示一篇常規的南北朝時代知名短文」，要是放個故意而做的奇文（況且還是今人作品）就反而做作了。
