### ISSUE TITLE
網頁一直載入不停

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-autoderiver#48]
網頁有時會一直載入不停，firefox左下顯示一句從什麼網接收資料不消失，要F5才停止載入

**Comment by ayaka14732** [comment]
具體是哪個站點的問題？

**Comment by 307587** [comment]
「從https://autoderiver-1305783649.cos.accelerate.myqcloud.com接收資料...」

**Comment by ayaka14732** [comment]
你身處何處？

ping autoderiver-1305783649.cos.accelerate.myqcloud.com 能否連接？

**Comment by ayaka14732** [comment]
不清楚是什麼問題，所以先關閉，待下次出現問題再打開
