### ISSUE TITLE
人手指定輸出格式的「\」轉義／跳脫符無效，會解析爲字面「\」

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-autoderiver#49]
例如中原音韻推導選項「異讀分隔符（留空則爲換行）」預設爲`\n`，留空時正確換行，人手指定`\n`卻會解析爲字面「\n」，`\t`等的轉義符同理。

**Comment by graphemecluster** [comment]
我個人認為這是 expected behaviour，畢竟沒有電腦背景的人不會懂 escape character。

（因此是我的話我會寫：）
```js
[
  // ...
  ['異讀分隔符', [1,
    { text: '空格', value: ' ' },
    { text: '定位', value: '\t' },
    { text: '換行', value: '\n' },
    '自訂',
  ]],
  ['自訂異讀分隔符', '', { hidden: 選項.異讀分隔符 !== '自訂' }],
  // ...
]
```
也看看 @syimyuzya 怎麼看～

**Comment by syimyuzya** [comment]
沒錯，這是預期行為。

使用者在選項的輸入框中輸入的內容，自然應當先「原封不動」地遞給程式，然後由程式按照是否需要，再執行格式解析或轉換。
