### ISSUE TITLE
允許停用或隱藏 `<option>`

### ISSUE THREAD

**Issue by graphemecluster** [nk2028/tshet-uinh-autoderiver#50]
若果把 https://github.com/nk2028/tshet-uinh-autoderiver/blob/b105b69fde36264f14ff5effb45d261e2ebc13b5/src/Classes/ParameterSet.tsx#L143-L150 改成
```js
 {options.flatMap((option, i) => {
   if (option["hidden"]) {
     return [];
   }
   const { value, text } = option;
   return [
     <option key={i} value={i} disabled={!!option["disabled"]}>
       {text ?? String(value)}
     </option>,
   ];
 })}
```
則有一個問題，以 https://github.com/nk2028/tshet-uinh-examples/pull/60#discussion_r1854160676 作例，若寫成
```js
  ['調式', [8,
    '調值（趙元任）', '調值（王璞）', '調線（趙元任）', '調線（王璞）',
    { value: '附標', hidden: 選項.注音符號 !== false }, '調號上標', '調號', '調符',
  ]],
```
則，若用户選擇「附標」後勾選「注音符號」，此時選擇仍為「附標」，但因 `<select>` 無此 `<option>` value，介面會顯示成第一個 `<option>`，即「調值（趙元任）」，但我們未有機制確保選項已加入 `{ reset: 選項.注音符號 !== false }`，`disabled` 亦同。
徵求 @syimyuzya 意見。

**Comment by syimyuzya** [comment]
注意「選項支援 disabled」並不能「只在推導器上做」，因為推導方案**並非僅在推導器上執行，也可能利用 tshet-uinh-deriver-tools 的 JS API，以程式碼呼叫使用**。

用 JS API 時，其 `選項` 引數會為使用者未指定的選項「自動填入預設值」，此時就需要面臨一個問題：hidden 和 disable 的項目，若使用者的引數中未指定，是要當做不存在（最終傳入方案的 `選項` 無此項），還是仍自動填入預設值並傳入方案？

我的建議是模仿 HTML form 的提交行為：hidden 的項目仍然傳入，但 disable 的項目不傳入（而如果既要隱藏又不要傳入，那就兩者均指定）。這樣的話，hidden 是僅影響 GUI 不影響 JS API 的，可以僅在推導器上做，但 disabled 不僅影響 GUI 也影響 JS API 行為，所以要先在 tshet-uinh-deriver-tools 中支援它才可以。

【順帶，還有一個行為細節：JS API 還額外支援傳入方案並未列出的選項（比如之前版本的切拼方案就做過，作為「不對外開放」的開發人員選項），此時如果某選項是 disabled，但使用者以 JS API 呼叫時卻指定了該項的值，則最好仍以使用者為優先，仍傳入該項。

**Comment by syimyuzya** [comment]
這樣的 GUI 動態行為，應該用動態產生 option 列表（及預設值），並用 reset 來實現。

新版的 unt 切韻擬音方案就做了這個效果（比如其「後低元音」選項），可以參考。

**Comment by syimyuzya** [comment]
另外，還有另一個改進空間，可以改善它的情況：想辦法讓方案更方便地 watch 某些選項的變動。【由於是 GUI 專屬功能，所以該功能最好不要與主要邏輯過於耦合（因為推導方案**不一定僅在推導器上執行**，也可能利用 tshet-uinh-deriver-tools 提供的 JS API，以程式呼叫使用）
