### ISSUE TITLE
加入自動填入單音字地位的功能

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-autoderiver#57]
如果推導器能自動填入單音字的地位就不用人手逐字填，要全文都標音時會省不少功夫。
nk2028/tshet-uinh-text-label#6

**Comment by graphemecluster** [comment]
為預置文章標上所有字音的設計是有意為之的。The Zen of Python 有一句話叫做：「Explicit is better than implicit.」寫上全部讀音不單止是為了確保推導結果載入速度，更是為了確保字音永遠保持唯一。日後字典可能會有新增發音，預設發音亦可能會有更改，用户亦可能會用自己的字典。再者，text-label 不僅是推導器，其他程式或工具也可以使用，所有程式語言應可以不依靠切韻程式庫而正確解釋 text-label。

事實上，我以前亦曾經問過 [Visual Fonts](https://visual-fonts.com/) 作者 Jon 相同問題，他的答覆是：

> This design decision is made to allow the user to lock in a pronunciation.  There is one reading right now but there may be more in the future; what is considered default may not be right.  When the user says 一.jat1, explicitly, it is to say that he absolutely mean this reading and no future edition/interpretation will change that.  (You may want to  see the [Invisible Markup](https://jon.hk/cantonese/invisible-markup-within-fonts/) article.)

至於［以 `字(音韻地位)` 格式複製輸入框的字］的確是一個功能，但目前可以簡單地以［以一個內容為 `return 音韻地位.描述` 的方案執行推導並複製推導結果］來解決，所以並不是一個大問題。

**Comment by 307587** [comment]
`return 音韻地位.描述`和`return 音韻地位`有什麼不同？我試了兩種導出的結果沒分別。

**Comment by untunt** [comment]
我认为推导器不应该提供“导出音韵地位”的选项，因为这个功能对普通用户来说是多余的，有使用这个功能的需求的用户应该自行掌握 `return 音韻地位.描述;` 代码

实际上这个需求是有先例的，[韵段离合指数统计工具](https://nk2028.shn.hk/rhyme-stat/)就需要以音韵地位作为输入，但只是在使用说明给出“將輸出的字在[推導器](https://nk2028.shn.hk/tshet-uinh-autoderiver/)中用 `return 音韻地位.描述;` 推導”这样的指示，而不是在推导器里增加这个选项

**Comment by graphemecluster** [comment]
> `return 音韻地位.描述`和`return 音韻地位`有什麼不同？我試了兩種導出的結果沒分別。

程式會將非函數傳回結果轉換成字串，即呼叫 `音韻地位.toString()`，而此函數會傳回 `音韻地位.描述` 的值。
